INSERT INTO Company (id, name, phone, founded, registered, approved) VALUES
    (null, 'Pierwsza firma', '123 123 123', '2012-12-12', '2019-03-01 12:20:12', 0),
    (null, 'Druga firma', '123 123 123', '2012-12-12', '2019-03-01 12:20:12', 0),
    (null, 'Trzecia firma', '123 123 123', '2012-12-12', '2019-03-01 12:20:12', 0),
    (null, 'Czwarta firma', '123 123 123', '2012-12-12', '2019-03-01 12:20:12', 0),
    (null, 'Piąta firma', '123 123 123', '2012-12-12', '2019-03-01 12:20:12', 0);

INSERT INTO COUNTRY (ID, ISO, IS_OBSOLETE, ISO3, NAME) VALUES
 (1, 'PL', false, 'POL', 'Poland'),
 (2, 'AD', false, 'AND', 'Andorra'),
 (3, 'AE', false, 'ARE', 'United Arab Emirates'),
 (4, 'AF', false, 'AFG', 'Afghanistan'),
 (5, 'AG', false, 'ATG', 'Antigua and Barbuda'),
 (6, 'AI', false, 'AIA', 'Anguilla'),
 (7, 'AL', false, 'ALB', 'Albania'),
 (8, 'AM', false, 'ARM', 'Armenia'),
 (9, 'AO', false, 'AGO', 'Angola'),
 (10, 'AQ', false, 'ATA', 'Antarctica'),
 (11, 'AR', false, 'ARG', 'Argentina'),
 (12, 'AS', false, 'ASM', 'American Samoa'),
 (13, 'AT', false, 'AUT', 'Austria'),
 (14, 'AU', false, 'AUS', 'Australia'),
 (15, 'AW', false, 'ABW', 'Aruba'),
 (16, 'AX', false, 'ALA', 'Aland Islands'),
 (17, 'AZ', false, 'AZE', 'Azerbaijan'),
 (18, 'BA', false, 'BIH', 'Bosnia and Herzegovina'),
 (19, 'BB', false, 'BRB', 'Barbados'),
 (21, 'BD', false, 'BGD', 'Bangladesh'),
 (22, 'BE', false, 'BEL', 'Belgium'),
 (23, 'BF', false, 'BFA', 'Burkina Faso'),
 (24, 'BG', false, 'BGR', 'Bulgaria'),
 (25, 'BH', false, 'BHR', 'Bahrain'),
 (26, 'BI', false, 'BDI', 'Burundi'),
 (27, 'BJ', false, 'BEN', 'Benin'),
 (28, 'BL', false, 'BLM', 'Saint Barthelemy'),
 (29, 'BM', false, 'BMU', 'Bermuda'),
 (31, 'BN', false, 'BRN', 'Brunei'),
 (32, 'BO', false, 'BOL', 'Bolivia'),
 (33, 'BQ', false, 'BES', 'Bonaire, Saint Eustatius and Saba '),
 (34, 'BR', false, 'BRA', 'Brazil'),
 (35, 'BS', false, 'BHS', 'Bahamas'),
 (36, 'BT', false, 'BTN', 'Bhutan'),
 (37, 'BV', false, 'BVT', 'Bouvet Island'),
 (38, 'BW', false, 'BWA', 'Botswana'),
 (39, 'BY', false, 'BLR', 'Belarus'),
 (41, 'BZ', false, 'BLZ', 'Belize'),
 (42, 'CA', false, 'CAN', 'Canada'),
 (43, 'CC', false, 'CCK', 'Cocos Islands'),
 (44, 'CD', false, 'COD', 'Democratic Republic of the Congo'),
 (45, 'CF', false, 'CAF', 'Central African Republic'),
 (46, 'CG', false, 'COG', 'Republic of the Congo'),
 (47, 'CH', false, 'CHE', 'Switzerland'),
 (48, 'CI', false, 'CIV', 'Ivory Coast'),
 (49, 'CK', false, 'COK', 'Cook Islands'),
 (51, 'CL', false, 'CHL', 'Chile'),
 (52, 'CM', false, 'CMR', 'Cameroon'),
 (53, 'CN', false, 'CHN', 'China'),
 (54, 'CO', false, 'COL', 'Colombia'),
 (55, 'CR', false, 'CRI', 'Costa Rica'),
 (56, 'CU', false, 'CUB', 'Cuba'),
 (57, 'CV', false, 'CPV', 'Cape Verde')
